<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\BlackSharkHid.cs" Link="Devices\BlackSharkHid.cs" />
    <Compile Include="..\..\AtkMouseHid.cs" Link="Devices\AtkMouseHid.cs" />
  </ItemGroup>
</Project>
